### ISSUE TITLE
GitHub Pages not active

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-Malik-Y#2]
Hi @Malik-Y 

Please turn on the GitHub Pages Service so that I can preview your web page through a web server. 

The instructions to do so are in Brightspace under the Content Section entitled "GitHub". There is a video that walks everyone through the process. 

Thank you.

**Comment by Malik-Y** [comment]
Hello sir, sorry for the delay, I enabled everything, and I think everything should be fine now.
________________________________
From: Neil Mispelaar ***@***.***>
Sent: Monday, February 20, 2023 9:49 AM
To: imd1005-web-development-winter-2023/assignment-02-Malik-Y ***@***.***>
Cc: Malik Yakubu ***@***.***>; Assign ***@***.***>
Subject: [imd1005-web-development-winter-2023/assignment-02-Malik-Y] GitHub Pages not active (Issue #2)

[External Email]

Hi @Malik-Y<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMalik-Y&data=05%7C01%7Cmalikyakubu%40cmail.carleton.ca%7C052476d0c5994d798ac408db1351a8ed%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125013664386377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BpGzFLQ7FrGbHreCXiYLAMK5Umwl0O9nIkN12MaOHxk%3D&reserved=0>

Please turn on the GitHub Pages Service so that I can preview your web page through a web server.

The instructions to do so are in Brightspace under the Content Section entitled "GitHub". There is a video that walks everyone through the process.

Thank you.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fimd1005-web-development-winter-2023%2Fassignment-02-Malik-Y%2Fissues%2F2&data=05%7C01%7Cmalikyakubu%40cmail.carleton.ca%7C052476d0c5994d798ac408db1351a8ed%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125013664386377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XYzJXZqG8ozxwIzu78wZ7cBI%2F1iShw%2Fvmu3r0XkeJtU%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA6AEUI2VBX3FJFWGBZELP43WYN77JANCNFSM6AAAAAAVB672ZU&data=05%7C01%7Cmalikyakubu%40cmail.carleton.ca%7C052476d0c5994d798ac408db1351a8ed%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125013664386377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PguwMQWBoh%2F%2Fbg9kNfno53GebESfIWGC4oocp1ThB00%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>

This email contains links to content or websites. Always be cautious when opening external links or attachments.

Please visit https://carleton.ca/its/help-centre/report-phishing/ for information on reporting phishing messages.

When in doubt, the ITS Service Desk can provide assistance. https://carleton.ca/its/chat

-----End of Disclaimer-----

**Comment by neilmispelaar** [comment]
Awesome sauce. 

Will have a look and let you know if I see any other issues.

**Comment by neilmispelaar** [comment]
Thanks @Malik-Y for addressing. 

Can confirm that the site is up and running. Will close this Issue. 

https://imd1005-web-development-winter-2023.github.io/assignment-02-Malik-Y/
